version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - gitgraf

  gitgraf:
    build: .
    image: gitgraf
    depends_on:
      - mongodb
    networks:
      - gitgraf
    environment:
      MONGO_URI: mongodb://mongodb:27017

networks:
  gitgraf:
