version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - gitraph

  gitraph:
    build: .
    image: gitraph
    depends_on:
      - mongodb
    networks:
      - gitraph
    environment:
      MONGO_URI: mongodb://mongodb:27017

networks:
  gitraph:
